//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
import { toQueryString } from "./utils";
export interface AdRequest {
  contextKeys: string[];
}

export interface Ad {
  redirectURL: string;
  text: string;
}

export interface AdResponse {
  ads: Ad[];
}


export class AdClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  public async get(request: AdRequest): Promise<AdResponse> {
    const response = await fetch(`${this.baseUrl}/ad?${toQueryString(request)}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }
}
