// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// eslint-disable @typescript-eslint/no-unused-vars
//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
//
export interface HttpRequest<Body> {
  method: string;
  path: string;
  pathParameters: Map<string, string>;
  query: Map<string, string[]>;
  headers: Map<string, string[]>;
  body: Body;
}

export interface HttpResponse<Body> {
  status: number;
  headers: Map<string, string[]>;
  body: Body;
}

export interface Empty {
}


export class BuiltinClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }
}
