// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// eslint-disable @typescript-eslint/no-unused-vars
//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
//
export interface Item {
  productID: string;
  quantity: number;
}

export interface AddItemRequest {
  userID: string;
  item: Item;
}

export interface AddItemResponse {
}

export interface GetCartRequest {
  userID: string;
}

export interface Cart {
  userID: string;
  items: Item[];
}

export interface EmptyCartRequest {
  userID: string;
}

export interface EmptyCartResponse {
}


export class CartClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  public async addItem(request: AddItemRequest): Promise<AddItemResponse> {
    const path = `/cart/add`;
    const response = await fetch(`${this.baseUrl}${path}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }

  public async getCart(request: GetCartRequest): Promise<Cart> {
    const path = `/cart?@json=${encodeURIComponent(JSON.stringify(request))}`;
    const response = await fetch(`${this.baseUrl}${path}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }

  public async emptyCart(request: EmptyCartRequest): Promise<EmptyCartResponse> {
    const path = `/cart/empty`;
    const response = await fetch(`${this.baseUrl}${path}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }
}
