//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
import { toQueryString } from "./utils";
export interface Money {
  currencyCode: string;
  units: int;
  nanos: int;
}

export interface CreditCardInfo {
  number: string;
  cVV: int;
  expirationYear: int;
  expirationMonth: int;
}

export interface ChargeRequest {
  amount: Money;
  creditCard: CreditCardInfo;
}

export interface ChargeResponse {
  transactionID: string;
}


export class PaymentClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  public async charge(request: ChargeRequest): Promise<ChargeResponse> {
    const response = await fetch(`${this.baseUrl}/payment/charge`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }
}
