//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
import { toQueryString } from "./utils";
export interface ListRequest {
}

export interface Money {
  currencyCode: string;
  units: int;
  nanos: int;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  picture: string;
  priceUSD: Money;
  categories: string[];
}

export interface ListResponse {
  products: Product[];
}

export interface GetRequest {
  id: string;
}

export interface SearchRequest {
  query: string;
}

export interface SearchResponse {
  results: Product[];
}


export class ProductcatalogClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  public async list(request: ListRequest): Promise<ListResponse> {
    const response = await fetch(`${this.baseUrl}/productcatalog?${toQueryString(request)}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }

  public async get(request: GetRequest): Promise<Product> {
    const response = await fetch(`${this.baseUrl}/productcatalog/id?${toQueryString(request)}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }
}
