//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
// @ts-ignore ignore unused error in generated code
import { toQueryString } from "./utils";
export interface ListRequest {
  userID: string;
  userProductIDs: string[];
}

export interface ListResponse {
  productIDs: string[];
}


export class RecommendationClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  public async list(request: ListRequest): Promise<ListResponse> {
    const response = await fetch(`${this.baseUrl}/recommendation?${toQueryString(request)}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }

}
