//
// Automatically generated by
//     ____________ 
//    / __/_  __/ / 
//   / _/  / / / /__
//  /_/   /_/ /____/            
//
// @ts-ignore ignore unused error in generated code
import { toQueryString } from "./utils";
export interface Address {
  streetAddress: string;
  city: string;
  state: string;
  country: string;
  zipCode: number;
}

export interface Item {
  productID: string;
  quantity: number;
}

export interface ShippingRequest {
  address: Address;
  items: Item[];
}

export interface Money {
  currencyCode: string;
  units: number;
  nanos: number;
}

export interface ShipOrderResponse {
  id: string;
}


export class ShippingClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  public async getQuote(request: ShippingRequest): Promise<Money> {
    const response = await fetch(`${this.baseUrl}/shipping/quote`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }

  public async shipOrder(request: ShippingRequest): Promise<ShipOrderResponse> {
    const response = await fetch(`${this.baseUrl}/shipping/ship`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });if (!response.ok) {
      throw new Error(`Error: ${response.status}`);
    }

    return response.json();
  }
}
